In [1]:
import numpy as np
import scipy.linalg as lg
import pandas as pd

In [27]:
def power_iterate(A, p, k = 10):
    for i in range(k):
        p = np.dot(A.T, p)
        print("k=",i)
        print(p)
        print("sum=", p.sum())

In [19]:
A = np.array([
        [0,1,0],
        [0,0,1],
        [1,0,0]
    ])
A

array([[0, 1, 0],
       [0, 0, 1],
       [1, 0, 0]])

In [20]:
p = np.array([1,0,0])
p

array([1, 0, 0])

In [21]:
power_iterate(A, p)

k= 0
[0 1 0]
k= 1
[0 0 1]
k= 2
[1 0 0]
k= 3
[0 1 0]
k= 4
[0 0 1]
k= 5
[1 0 0]
k= 6
[0 1 0]
k= 7
[0 0 1]
k= 8
[1 0 0]
k= 9
[0 1 0]


In [22]:
A = np.array(
   [[0, 1/2, 1/2, 0, 0, 0],
    [1/2, 0, 1/2, 0, 0, 0],
    [0, 1, 0, 0, 0, 0],
    [0, 0, 1/3, 0, 1/3, 1/3],
    [0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1/2, 1/2, 0]]
)
A

array([[ 0.        ,  0.5       ,  0.5       ,  0.        ,  0.        ,
         0.        ],
       [ 0.5       ,  0.        ,  0.5       ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.33333333,  0.        ,  0.33333333,
         0.33333333],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.5       ,  0.5       ,
         0.        ]])

In [30]:
p = np.ones(6)/6
power_iterate(A, p, k = 100)

k= 0
[ 0.08333333  0.25        0.22222222  0.08333333  0.13888889  0.05555556]
sum= 0.833333333333
k= 1
[ 0.125       0.26388889  0.19444444  0.02777778  0.05555556  0.02777778]
sum= 0.694444444444
k= 2
[ 0.13194444  0.25694444  0.2037037   0.01388889  0.02314815  0.00925926]
sum= 0.638888888889
k= 3
[ 0.12847222  0.26967593  0.19907407  0.00462963  0.00925926  0.00462963]
sum= 0.615740740741
k= 4
[ 0.13483796  0.26331019  0.20061728  0.00231481  0.00385802  0.00154321]
sum= 0.606481481481
k= 5
[ 0.13165509  0.26803627  0.19984568  0.0007716   0.00154321  0.0007716 ]
sum= 0.60262345679
k= 6
[  1.34018133e-01   2.65673225e-01   2.00102881e-01   3.85802469e-04
   6.43004115e-04   2.57201646e-04]
sum= 0.601080246914
k= 7
[  1.32836613e-01   2.67111947e-01   1.99974280e-01   1.28600823e-04
   2.57201646e-04   1.28600823e-04]
sum= 0.600437242798
k= 8
[  1.33555974e-01   2.66392586e-01   2.00017147e-01   6.43004115e-05
   1.07167353e-04   4.28669410e-05]
sum= 0.600180041152
k= 9
[  1.3319629

In [3]:
a = set([1,2,3])
b = set([2,3,4])

In [6]:
a.intersection(b)
a

{1, 2, 3}

In [10]:
a.add(4)
a

{1, 2, 3, 4}

In [11]:
a.append(4)

AttributeError: 'set' object has no attribute 'append'

In [2]:
from collections import defaultdict

In [3]:
a = defaultdict(defaultdict(lambda: 0))

TypeError: first argument must be callable or None

In [4]:
a = defaultdict(lambda: defaultdict(int))

In [5]:
a["a"]["B"] += 2

In [6]:
a

defaultdict(<function __main__.<lambda>>, {'a': defaultdict(int, {'B': 2})})

In [7]:
a["a"]

defaultdict(int, {'B': 2})

In [8]:
a["a"]["b"]

0

In [9]:
a = {"a" : 10, "b": 1}

In [11]:
max(a.values())

10